### ISSUE TITLE
Update site <title>/OpenGraph to improve SEO

### ISSUE THREAD

**Issue by garrettmaring** [engi-network/website#122]
Update meta tags `title` to 'Engi Network' and `description` to 'Affordable Engineering On-Demand'

![CleanShot 2023-08-20 at 19 05 03@2x](https://github.com/engi-network/website/assets/8270120/bd435629-143d-450c-bd20-cbf13f137907)
![CleanShot 2023-08-20 at 19 04 31@2x](https://github.com/engi-network/website/assets/8270120/1acd18ba-e9c8-4d08-9310-0827f8fc60d7)

**Comment by mikemaring** [comment]
Just testing a comment
