### ISSUE TITLE
Update currency component tooltip to include ETH & USD

### ISSUE THREAD

**Issue by jfwu90** [engi-network/website#137]
Add USD amount next to engi value since 0.01 is very small.

**Comment by garrettmaring** [comment]
<img width="256" alt="Screenshot 2023-10-02 at 12 17 15 PM" src="https://github.com/engi-network/website/assets/8270120/835ccfa4-8dc2-459b-ad08-54b2b000ca0a">

**Comment by jfwu90** [comment]
@garrettmaring should it include ETH if they have the same value? Also, is there any point in showing WOZ to the regular user?

**Comment by garrettmaring** [comment]
I like the idea of showing all 3 for now for educational purposes.

        | ETH: 1.001 | USD: $2000 |
| WOZ: 10101010101001100101010101 |

Can also through in a QoL to copy the Woz amount on click
